language: ruby
bundler_args: --without development
rvm:
    - 1.9.3
    - 2.0.0
    - ruby-head
env:
    - DB=sqlite DISPLAY=":99.0"
matrix:  
  allow_failures:
    - rvm: ruby-head

branches:
    only:
        - master
        - develop
        - /^release.*$/
        - /^hotfix.*$/

before_script:
    - rake db:create
    - rake db:migrate
    - rake db:test:prepare
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - bundle exec rake test
    - bundle exec rake jasmine:ci
notifications:
    webhooks:
        urls:
            - http://life.jstfy.com/hook
        on_succes: always
        on_failure: never
